In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/clustering_segmentation_Amz_Customers.csv')
display(df.head(3))

   Annual_Income_k  Spending_Score_1_100  Age  Frequency_of_Purchase
0              107                    15   23                     16
1               56                    92   32                     13
2               40                    98   60                     42

In [10]:
from sklearn.datasets import fetch_california_housing
# display(fetch_california_housing().values())
print("Loading California Housing Data...")
housing = fetch_california_housing()
X = pd.DataFrame(housing.data, columns=housing.feature_names)
y = pd.Series(housing.target, name="MedianHouseValue")
print(f"Dataset loaded with {X.shape[0]} rows and {X.shape[1]} features.\n")

display(X.head())

Loading California Housing Data...
Dataset loaded with 20640 rows and 8 features.

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25